spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC
    username: root
    password: gmldnjs5695
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: verySecretKeyChangeMe
  expirationMs: 3600000
